version: '3.8'

services:
  comfyui:
    build: .
    container_name: comfyui-remote
    restart: unless-stopped
    environment:
      - COMFYUI_USERNAME=admin
      - COMFYUI_PASSWORD=${COMFYUI_PASSWORD:-changeme123}
      - COMFYUI_HOST=0.0.0.0
      - COMFYUI_PORT=8188
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "80:80"
      - "8188:8188"
    volumes:
      # Persistent model storage
      - ./models:/home/comfyui/ComfyUI/models
      - ./custom_nodes:/home/comfyui/ComfyUI/custom_nodes
      - ./input:/home/comfyui/ComfyUI/input
      - ./output:/home/comfyui/ComfyUI/output
      - ./workflows:/home/comfyui/ComfyUI/workflows
      # Custom nginx config (optional)
      - ./nginx/nginx.conf:/etc/nginx/sites-available/comfyui:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Tailscale sidecar for secure access
  tailscale:
    image: tailscale/tailscale:latest
    container_name: comfyui-tailscale
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=comfyui-server
      - TS_EXTRA_ARGS=--advertise-tags=tag:comfyui
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - comfyui

  # Cloudflare tunnel (alternative to Tailscale)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: comfyui-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - comfyui
    profiles:
      - cloudflare

  # Reverse proxy with SSL termination
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: comfyui-proxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=${DOMAIN:-localhost}
    profiles:
      - ssl

  # Let's Encrypt companion
  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: comfyui-letsencrypt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=comfyui-proxy
    depends_on:
      - nginx-proxy
    profiles:
      - ssl

volumes:
  tailscale-state:

networks:
  default:
    name: comfyui-network